document.write('Текст.');
document.write('<br>');
document.write('<i>ТеКсТ</i>');
document.write('<br>');
let str = 'Курсив  переменной';
document.write('<i>'+ str + '</i>');
document.write('<br>');
document.write('1<br>');
document.write('2<br>');
document.write('3<br>');
document.write('4<br>');
document.write('5<br>');